[package]
name = "rust_sqlc_test"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde_json = "1.0.139"
